#!/bin/bash

# Pastas para Backup 
NEXTCLOUD_CONFIG="/var/snap/nextcloud/common"
NEXTCLOUD_DATA="/path/to/Nextcloud/data"
PLEX_CONFIG="/var/snap/plexmediaserver/common/Library/Application Support"

# Pastas para Restauração Nextcloud snap 
CONFIG_NC_RESTORE="var/snap/nextcloud/common/backups"
CONFIG_PLEX_RESTORE="var/snap/plexmediaserver/common/Library/Application Support/Plex Media Server"

# Ponto de Montagem do HD externo 
DESTINATIONDIR="/path/to/mont/HD-Externo"

# Caminho do Hd Externo (checar "fdisk -l")
DEVICE="/dev/sxx"

# Arquivo Tar-GZ
ARQUIVO_TAR="$DESTINATIONDIR/Nc-Configs-$(date +%Y-%m-%d_%H-%M).tar.gz"

# Opção Para incluir multiplos diretórios use: -T "/nome/do/Arquivo.txt

TARLIST="/path/to/Nextcloud_Plex/tar-include-lst"

# Lista de inclusao Exclusão

# Use --exclude-from
EXCLUDELIST="/path/to/exclude-lst" 

# Use --files-from
INCLUDELIST="/path/to/include-lst"

# Arquivos de Log		
LOGFILE_PATH="/path/to/log/Backup-$(date +%Y-%m-%d_%H-%M).txt"
RESTLOGFILE_PATH="/path/to/log/Restore-$(date +%Y-%m-%d_%H-%M).txt"

